version: 2.1

jobs:
  trufflehog-scan:
    docker:
      - image: python:3.7.9
    steps:
      - checkout
      - run:
          name: Install TruffleHog
          command: pip install trufflehog
      - run:
          name: Scan for Secrets
          command: |
            trufflehog filesystem ./
