version: 2.1

orbs:
  ggshield: gitguardian/ggshield@1.1.4

jobs:
  ggshield-scan:
    executor: ggshield/default
    steps:
      - checkout
      - ggshield/scan:
          base_revision: << pipeline.git.base_revision >>
          revision: << pipeline.git.revision >>

workflows:
  main:
    jobs:
      - ggshield-scan